# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
- job: build
  timeoutInMinutes: 360
  cancelTimeoutInMinutes: 10
  pool:
    vmImage: 'Ubuntu-16.04'
  
  steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'
      timeoutInMinutes: 10

    - script: |
        #echo Add other tasks to build, test, and deploy your project.
        #echo See https://aka.ms/yaml
        ls
        pwd
        curl https://mirrors.tuna.tsinghua.edu.cn/git/git-repo -o repo
        chmod +x repo
        ls
        export PATH="$(pwd):$PATH"
        echo $PATH
        git clone https://github.com/idevstudio/builttools buildtool
        chmod +x buildtool/bc
        export PATH="$(pwd)/buildtool:$PATH"
        bc --version
        mkdir repohome
        cd repohome
        repo init -u https://github.com/idevstudio/android.git -b lineage-16.0
        repo sync --force-sync -j16
        du -sk
        ls
        source build/envsetup.sh
        breakfast libra
        #more .repo/manifest.xml
        #more .repo/local_manifests/roomservice.xml
        brunch libra
      displayName: 'Run a multi-line script'
      timeoutInMinutes: 350