# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    #echo Add other tasks to build, test, and deploy your project.
    #echo See https://aka.ms/yaml
    ls
    pwd
    curl https://mirrors.tuna.tsinghua.edu.cn/git/git-repo -o repo
    chmod +x repo
    ls
    export PATH="$(pwd):$PATH"
    echo $PATH
    mkdir repohome
    cd repohome
    repo init -u https://github.com/LineageOS/android.git -b lineage-15.1
    repo sync
    du -sk
    ls
    source build/envsetup.sh
    breakfast libra
    brunch libra
  displayName: 'Run a multi-line script'
